# 应用名称
server:
  port: 8090
  ssl:
    key-store: classpath:pp.yishengxiongpe.cn.jks
    key-store-password: no2e3nr6hxc9
    key-store-type: JKS
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  application:
    name: payment-dome
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yanhaiyun?serverTimezone=GMT
      username: root
      password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql日志
  mapper-locations: classpath:com/yhgc/api/mapper/xml/*.xml

redis:
  host: 127.0.0.1
  post: 6379

#ftp相关  这里的ip是ftp服务器ip, 我是在已有服务器172.16.1.13上测试的,不是在刚设置的172.16.1.20上测试的,填写自己的ftp服务器IP即可
ftp:
  account: ftptest
  password: Yi123456
  port: 21
  server: 120.79.64.245
  fileFolder: /provide
  #ftp 上传访问头
  url: http://120.79.64.245:8999