# 应用名称
server:
  port: 8090
  ssl:
    key-store: classpath:pp.yishengxiongpe.cn.jks
    key-store-password: no2e3nr6hxc9
    key-store-type: JKS
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  application:
    name: payment-dome
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yanhaiyun?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql日志
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/yhgc/api/mapper/xml/*.xml
  type-aliases-package: com.yhgc.api.entity

redis:
  host: 127.0.0.1
  post: 6379
